# Stubs for networkx.algorithms.bipartite.centrality (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any
from _typeshed import Incomplete

def degree_centrality(G: Any, nodes: Any) -> Incomplete: ...
def betweenness_centrality(G: Any, nodes: Any) -> Incomplete: ...
def closeness_centrality(G: Any, nodes: Any, normalized: bool = ...) -> Incomplete: ...
