# Stubs for networkx.algorithms.bipartite.cluster (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

def latapy_clustering(G: Any, nodes: Any | None = ..., mode: str = ...) -> Any: ...

clustering = latapy_clustering

def average_clustering(G: Any, nodes: Any | None = ..., mode: str = ...) -> Any: ...
def robins_alexander_clustering(G: Any) -> Any: ...
