# Stubs for networkx.algorithms.bipartite.covering (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from _typeshed import Incomplete

def min_edge_cover(
    G: Incomplete, matching_algorithm: Incomplete | None = ...
) -> Incomplete: ...
