# Stubs for networkx.algorithms.bipartite.covering (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any
from _typeshed import Incomplete

def min_edge_cover(G: Any, matching_algorithm: Any | None = ...) -> Incomplete: ...
