# Stubs for networkx.algorithms.bipartite.edgelist (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from _typeshed import Incomplete

def write_edgelist(
    G: Incomplete,
    path: Incomplete,
    comments: str = ...,
    delimiter: str = ...,
    data: bool = ...,
    encoding: str = ...,
) -> None: ...
def generate_edgelist(
    G: Incomplete, delimiter: str = ..., data: bool = ...
) -> None: ...
def parse_edgelist(
    lines: Incomplete,
    comments: str = ...,
    delimiter: Incomplete | None = ...,
    create_using: Incomplete | None = ...,
    nodetype: Incomplete | None = ...,
    data: bool = ...,
) -> Incomplete: ...
def read_edgelist(
    path: Incomplete,
    comments: str = ...,
    delimiter: Incomplete | None = ...,
    create_using: Incomplete | None = ...,
    nodetype: Incomplete | None = ...,
    data: bool = ...,
    edgetype: Incomplete | None = ...,
    encoding: str = ...,
) -> Incomplete: ...
