# Stubs for networkx.algorithms.bipartite.generators (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from _typeshed import Incomplete

def complete_bipartite_graph(
    n1: Incomplete, n2: Incomplete, create_using: Incomplete | None = ...
) -> Incomplete: ...
def configuration_model(
    aseq: Incomplete,
    bseq: Incomplete,
    create_using: Incomplete | None = ...,
    seed: Incomplete | None = ...,
) -> Incomplete: ...
def havel_hakimi_graph(
    aseq: Incomplete, bseq: Incomplete, create_using: Incomplete | None = ...
) -> Incomplete: ...
def reverse_havel_hakimi_graph(
    aseq: Incomplete, bseq: Incomplete, create_using: Incomplete | None = ...
) -> Incomplete: ...
def alternating_havel_hakimi_graph(
    aseq: Incomplete, bseq: Incomplete, create_using: Incomplete | None = ...
) -> Incomplete: ...
def preferential_attachment_graph(
    aseq: Incomplete,
    p: Incomplete,
    create_using: Incomplete | None = ...,
    seed: Incomplete | None = ...,
) -> Incomplete: ...
def random_graph(
    n: Incomplete,
    m: Incomplete,
    p: Incomplete,
    seed: Incomplete | None = ...,
    directed: bool = ...,
) -> Incomplete: ...
def gnmk_random_graph(
    n: Incomplete,
    m: Incomplete,
    k: Incomplete,
    seed: Incomplete | None = ...,
    directed: bool = ...,
) -> Incomplete: ...
