# Stubs for networkx.algorithms.bipartite.matrix (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

def biadjacency_matrix(
    G: Any, row_order: Any, column_order: Any | None = ..., dtype: Any | None = ..., weight: str = ..., format: str = ...
) -> Any: ...
def from_biadjacency_matrix(A: Any, create_using: Any | None = ..., edge_attribute: str = ...) -> Any: ...
