# Stubs for networkx.algorithms.bipartite.matrix (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from _typeshed import Incomplete

def biadjacency_matrix(
    G: Incomplete,
    row_order: Incomplete,
    column_order: Incomplete | None = ...,
    dtype: Incomplete | None = ...,
    weight: str = ...,
    format: str = ...,
) -> Incomplete: ...
def from_biadjacency_matrix(
    A: Incomplete, create_using: Incomplete | None = ..., edge_attribute: str = ...
) -> Incomplete: ...
