# Stubs for networkx.algorithms.bipartite.redundancy (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any
from _typeshed import Incomplete

def node_redundancy(G: Any, nodes: Any | None = ...) -> Incomplete: ...
