# Stubs for networkx.algorithms.bipartite.redundancy (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from _typeshed import Incomplete

def node_redundancy(G: Incomplete, nodes: Incomplete | None = ...) -> Incomplete: ...
