# Stubs for networkx.algorithms.bipartite.spectral (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from _typeshed import Incomplete

def spectral_bipartivity(
    G: Incomplete, nodes: Incomplete | None = ..., weight: str = ...
) -> Incomplete: ...
