# Stubs for networkx.algorithms.bipartite.spectral (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any
from _typeshed import Incomplete

def spectral_bipartivity(
    G: Any, nodes: Any | None = ..., weight: str = ...
) -> Incomplete: ...
