# Stubs for networkx.relabel (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any, Optional

def relabel_nodes(G: Any, mapping: Any, copy: bool = ...): ...
def convert_node_labels_to_integers(G: Any, first_label: int = ..., ordering: str = ..., label_attribute: Optional[Any] = ...): ...
