# Stubs for networkx.relabel (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any, Optional, TypeVar, Dict, Union

from networkx.classes.digraph import DiGraph
from networkx.classes.graph import Graph

_X = TypeVar("_X")
_Y = TypeVar("_Y")


def relabel_nodes(G: DiGraph[_X], mapping: Dict[_X, _Y], copy: bool = ...) -> DiGraph[Union[_X,_Y]]: ...
def convert_node_labels_to_integers(G: Any, first_label: int = ..., ordering: str = ..., label_attribute: Optional[Any] = ...): ...
