# Stubs for networkx.relabel (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any, TypeVar

from networkx.classes.digraph import DiGraph

_X = TypeVar("_X")
_Y = TypeVar("_Y")

def relabel_nodes(G: DiGraph[_X], mapping: dict[_X, _Y], copy: bool = ...) -> DiGraph[_X | _Y]: ...
def convert_node_labels_to_integers(G: Any, first_label: int = ..., ordering: str = ..., label_attribute: Any | None = ...): ...
