# Stubs for networkx.version (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from _typeshed import Incomplete

version: str
date: str
dev: bool
version_info: Incomplete
date_info: Incomplete
vcs_info: Incomplete
