# Stubs for networkx.readwrite.json_graph.adjacency (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from _typeshed import Incomplete

def adjacency_data(G: Incomplete, attrs: Incomplete = ...) -> Incomplete: ...
def adjacency_graph(
    data: Incomplete,
    directed: bool = ...,
    multigraph: bool = ...,
    attrs: Incomplete = ...,
) -> Incomplete: ...
