# Stubs for networkx.readwrite.json_graph.adjacency (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any
from _typeshed import Incomplete

def adjacency_data(G: Any, attrs: Any = ...) -> Incomplete: ...
def adjacency_graph(
    data: Any, directed: bool = ..., multigraph: bool = ..., attrs: Any = ...
) -> Incomplete: ...
