# Stubs for networkx.readwrite.json_graph.cytoscape (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from _typeshed import Incomplete

def cytoscape_data(G: Incomplete, attrs: Incomplete | None = ...) -> Incomplete: ...
def cytoscape_graph(data: Incomplete, attrs: Incomplete | None = ...) -> Incomplete: ...
