# Stubs for networkx.readwrite.json_graph.cytoscape (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

def cytoscape_data(G: Any, attrs: Any | None = ...) -> Any: ...
def cytoscape_graph(data: Any, attrs: Any | None = ...) -> Any: ...
