# Stubs for networkx.readwrite.json_graph.jit (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any
from _typeshed import Incomplete

def jit_graph(data: Any, create_using: Any | None = ...) -> Incomplete: ...
def jit_data(G: Any, indent: Any | None = ...) -> Incomplete: ...
