# Stubs for networkx.readwrite.json_graph.jit (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from _typeshed import Incomplete

def jit_graph(
    data: Incomplete, create_using: Incomplete | None = ...
) -> Incomplete: ...
def jit_data(G: Incomplete, indent: Incomplete | None = ...) -> Incomplete: ...
