# Stubs for networkx.readwrite.json_graph.node_link (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from _typeshed import Incomplete

def node_link_data(G: Incomplete, attrs: Incomplete | None = ...) -> Incomplete: ...
def node_link_graph(
    data: Incomplete,
    directed: bool = ...,
    multigraph: bool = ...,
    attrs: Incomplete | None = ...,
) -> Incomplete: ...
