# Stubs for networkx.readwrite.json_graph.node_link (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any
from networkx.classes.graph import Graph
def node_link_data(
    G: Graph,
    attrs: dict[str, str] | None = ...,
    source: str = ...,
    target: str = ...,
    name: str = ...,
    key: str = ...,
    link: str = ...,
) -> dict: ...
def node_link_graph(
    data: Any, directed: bool = ..., multigraph: bool = ..., attrs: Any | None = ...
) -> Any: ...
