# Stubs for networkx.readwrite.json_graph.node_link (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

def node_link_data(G: Any, attrs: Any | None = ...) -> Any: ...
def node_link_graph(data: Any, directed: bool = ..., multigraph: bool = ..., attrs: Any | None = ...) -> Any: ...
