# Stubs for networkx.readwrite.json_graph.tree (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from _typeshed import Incomplete

def tree_data(
    G: Incomplete, root: Incomplete, attrs: Incomplete = ...
) -> Incomplete: ...
def tree_graph(data: Incomplete, attrs: Incomplete = ...) -> Incomplete: ...
