# Stubs for networkx.algorithms.flow.boykovkolmogorov (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any
from _typeshed import Incomplete

def boykov_kolmogorov(
    G: Any,
    s: Any,
    t: Any,
    capacity: str = ...,
    residual: Any | None = ...,
    value_only: bool = ...,
    cutoff: Any | None = ...,
) -> Incomplete: ...
