# Stubs for networkx.algorithms.flow.capacityscaling (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from _typeshed import Incomplete

def capacity_scaling(
    G: Incomplete,
    demand: str = ...,
    capacity: str = ...,
    weight: str = ...,
    heap: Incomplete = ...,
) -> Incomplete: ...
