# Stubs for networkx.algorithms.flow.dinitz_alg (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from _typeshed import Incomplete

def dinitz(
    G: Incomplete,
    s: Incomplete,
    t: Incomplete,
    capacity: str = ...,
    residual: Incomplete | None = ...,
    value_only: bool = ...,
    cutoff: Incomplete | None = ...,
) -> Incomplete: ...
