# Stubs for networkx.algorithms.flow.dinitz_alg (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

def dinitz(
    G: Any, s: Any, t: Any, capacity: str = ..., residual: Any | None = ..., value_only: bool = ..., cutoff: Any | None = ...
) -> Any: ...
