# Stubs for networkx.algorithms.flow.edmondskarp (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

from networkx.algorithms.flow.utils import *

def edmonds_karp(
    G: Any, s: Any, t: Any, capacity: str = ..., residual: Any | None = ..., value_only: bool = ..., cutoff: Any | None = ...
) -> Any: ...
