# Stubs for networkx.algorithms.flow.gomory_hu (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from _typeshed import Incomplete

def gomory_hu_tree(
    G: Incomplete, capacity: str = ..., flow_func: Incomplete | None = ...
) -> Incomplete: ...
