# Stubs for networkx.algorithms.flow.gomory_hu (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from .edmondskarp import edmonds_karp
from typing import Any, Optional

def gomory_hu_tree(G: Any, capacity: str = ..., flow_func: Optional[Any] = ...): ...
