# Stubs for networkx.algorithms.flow.gomory_hu (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any
from _typeshed import Incomplete

def gomory_hu_tree(
    G: Any, capacity: str = ..., flow_func: Any | None = ...
) -> Incomplete: ...
