# Stubs for networkx.algorithms.flow.maxflow (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any
from _typeshed import Incomplete

def maximum_flow(
    flowG: Any,
    _s: Any,
    _t: Any,
    capacity: str = ...,
    flow_func: Any | None = ...,
    **kwargs: Any
) -> Incomplete: ...
def maximum_flow_value(
    flowG: Any,
    _s: Any,
    _t: Any,
    capacity: str = ...,
    flow_func: Any | None = ...,
    **kwargs: Any
) -> Incomplete: ...
def minimum_cut(
    flowG: Any,
    _s: Any,
    _t: Any,
    capacity: str = ...,
    flow_func: Any | None = ...,
    **kwargs: Any
) -> Incomplete: ...
def minimum_cut_value(
    flowG: Any,
    _s: Any,
    _t: Any,
    capacity: str = ...,
    flow_func: Any | None = ...,
    **kwargs: Any
) -> Incomplete: ...
