# Stubs for networkx.algorithms.flow.maxflow (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from _typeshed import Incomplete

def maximum_flow(
    flowG: Incomplete,
    _s: Incomplete,
    _t: Incomplete,
    capacity: str = ...,
    flow_func: Incomplete | None = ...,
    **kwargs: Incomplete
) -> Incomplete: ...
def maximum_flow_value(
    flowG: Incomplete,
    _s: Incomplete,
    _t: Incomplete,
    capacity: str = ...,
    flow_func: Incomplete | None = ...,
    **kwargs: Incomplete
) -> Incomplete: ...
def minimum_cut(
    flowG: Incomplete,
    _s: Incomplete,
    _t: Incomplete,
    capacity: str = ...,
    flow_func: Incomplete | None = ...,
    **kwargs: Incomplete
) -> Incomplete: ...
def minimum_cut_value(
    flowG: Incomplete,
    _s: Incomplete,
    _t: Incomplete,
    capacity: str = ...,
    flow_func: Incomplete | None = ...,
    **kwargs: Incomplete
) -> Incomplete: ...
