# Stubs for networkx.algorithms.flow.networksimplex (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from _typeshed import Incomplete

def network_simplex(
    G: Incomplete, demand: str = ..., capacity: str = ..., weight: str = ...
) -> Incomplete: ...
