# Stubs for networkx.algorithms.flow.preflowpush (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

def preflow_push(
    G: Any,
    s: Any,
    t: Any,
    capacity: str = ...,
    residual: Any | None = ...,
    global_relabel_freq: int = ...,
    value_only: bool = ...,
) -> Any: ...
