# Stubs for networkx.algorithms.flow.preflowpush (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from _typeshed import Incomplete

def preflow_push(
    G: Incomplete,
    s: Incomplete,
    t: Incomplete,
    capacity: str = ...,
    residual: Incomplete | None = ...,
    global_relabel_freq: int = ...,
    value_only: bool = ...,
) -> Incomplete: ...
