# Stubs for networkx.algorithms.flow.shortestaugmentingpath (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

from .utils import *

def shortest_augmenting_path(
    G: Any,
    s: Any,
    t: Any,
    capacity: str = ...,
    residual: Any | None = ...,
    value_only: bool = ...,
    two_phase: bool = ...,
    cutoff: Any | None = ...,
) -> Any: ...
