# Stubs for networkx.algorithms.tree.mst (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from _typeshed import Incomplete

def minimum_spanning_edges(
    G: Incomplete,
    algorithm: str = ...,
    weight: str = ...,
    keys: bool = ...,
    data: bool = ...,
    ignore_nan: bool = ...,
) -> Incomplete: ...
def maximum_spanning_edges(
    G: Incomplete,
    algorithm: str = ...,
    weight: str = ...,
    keys: bool = ...,
    data: bool = ...,
    ignore_nan: bool = ...,
) -> Incomplete: ...
def minimum_spanning_tree(
    G: Incomplete, weight: str = ..., algorithm: str = ..., ignore_nan: bool = ...
) -> Incomplete: ...
def maximum_spanning_tree(
    G: Incomplete, weight: str = ..., algorithm: str = ..., ignore_nan: bool = ...
) -> Incomplete: ...
