# Stubs for networkx.algorithms.tree.operations (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

def join(rooted_trees: Any, label_attribute: Any | None = ...) -> Any: ...
