# Stubs for networkx.algorithms.tree.operations (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from _typeshed import Incomplete

def join(
    rooted_trees: Incomplete, label_attribute: Incomplete | None = ...
) -> Incomplete: ...
