# Stubs for networkx.algorithms.centrality.betweenness_subset (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from _typeshed import Incomplete

def betweenness_centrality_subset(
    G: Incomplete,
    sources: Incomplete,
    targets: Incomplete,
    normalized: bool = ...,
    weight: Incomplete | None = ...,
) -> Incomplete: ...
def edge_betweenness_centrality_subset(
    G: Incomplete,
    sources: Incomplete,
    targets: Incomplete,
    normalized: bool = ...,
    weight: Incomplete | None = ...,
) -> Incomplete: ...
def betweenness_centrality_source(
    G: Incomplete,
    normalized: bool = ...,
    weight: Incomplete | None = ...,
    sources: Incomplete | None = ...,
) -> Incomplete: ...
