# Stubs for networkx.algorithms.centrality.betweenness (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any
from _typeshed import Incomplete

def betweenness_centrality(
    G: Any,
    k: Any | None = ...,
    normalized: bool = ...,
    weight: Any | None = ...,
    endpoints: bool = ...,
    seed: Any | None = ...,
) -> Incomplete: ...
def edge_betweenness_centrality(
    G: Any,
    k: Any | None = ...,
    normalized: bool = ...,
    weight: Any | None = ...,
    seed: Any | None = ...,
) -> Incomplete: ...
def edge_betweenness(
    G: Any,
    k: Any | None = ...,
    normalized: bool = ...,
    weight: Any | None = ...,
    seed: Any | None = ...,
) -> Incomplete: ...
