# Stubs for networkx.algorithms.centrality.betweenness (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from _typeshed import Incomplete

def betweenness_centrality(
    G: Incomplete,
    k: Incomplete | None = ...,
    normalized: bool = ...,
    weight: Incomplete | None = ...,
    endpoints: bool = ...,
    seed: Incomplete | None = ...,
) -> Incomplete: ...
def edge_betweenness_centrality(
    G: Incomplete,
    k: Incomplete | None = ...,
    normalized: bool = ...,
    weight: Incomplete | None = ...,
    seed: Incomplete | None = ...,
) -> Incomplete: ...
def edge_betweenness(
    G: Incomplete,
    k: Incomplete | None = ...,
    normalized: bool = ...,
    weight: Incomplete | None = ...,
    seed: Incomplete | None = ...,
) -> Incomplete: ...
