# Stubs for networkx.algorithms.centrality.closeness (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

def closeness_centrality(G: Any, u: Any | None = ..., distance: Any | None = ..., wf_improved: bool = ...) -> Any: ...
