# Stubs for networkx.algorithms.centrality.closeness (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from _typeshed import Incomplete

def closeness_centrality(
    G: Incomplete,
    u: Incomplete | None = ...,
    distance: Incomplete | None = ...,
    wf_improved: bool = ...,
) -> Incomplete: ...
