# Stubs for networkx.algorithms.centrality.current_flow_betweenness (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from _typeshed import Incomplete
from networkx.algorithms.centrality.flow_matrix import *

def approximate_current_flow_betweenness_centrality(
    G: Incomplete,
    normalized: bool = ...,
    weight: Incomplete | None = ...,
    dtype: Incomplete = ...,
    solver: str = ...,
    epsilon: float = ...,
    kmax: int = ...,
    seed: Incomplete | None = ...,
) -> Incomplete: ...
def current_flow_betweenness_centrality(
    G: Incomplete,
    normalized: bool = ...,
    weight: Incomplete | None = ...,
    dtype: Incomplete = ...,
    solver: str = ...,
) -> Incomplete: ...
def edge_current_flow_betweenness_centrality(
    G: Incomplete,
    normalized: bool = ...,
    weight: Incomplete | None = ...,
    dtype: Incomplete = ...,
    solver: str = ...,
) -> Incomplete: ...
