# Stubs for networkx.algorithms.centrality.current_flow_closeness (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from _typeshed import Incomplete
from networkx.algorithms.centrality.flow_matrix import *

def current_flow_closeness_centrality(
    G: Incomplete,
    weight: Incomplete | None = ...,
    dtype: Incomplete = ...,
    solver: str = ...,
) -> Incomplete: ...

information_centrality = current_flow_closeness_centrality
