# Stubs for networkx.algorithms.centrality.degree_alg (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any
from _typeshed import Incomplete

def degree_centrality(G: Any) -> Incomplete: ...
def in_degree_centrality(G: Any) -> Incomplete: ...
def out_degree_centrality(G: Any) -> Incomplete: ...
