# Stubs for networkx.algorithms.centrality.dispersion (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

def dispersion(
    G: Any, u: Any | None = ..., v: Any | None = ..., normalized: bool = ..., alpha: float = ..., b: float = ..., c: float = ...
) -> Any: ...
