# Stubs for networkx.algorithms.centrality.dispersion (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from _typeshed import Incomplete

def dispersion(
    G: Incomplete,
    u: Incomplete | None = ...,
    v: Incomplete | None = ...,
    normalized: bool = ...,
    alpha: float = ...,
    b: float = ...,
    c: float = ...,
) -> Incomplete: ...
