# Stubs for networkx.algorithms.centrality.eigenvector (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from _typeshed import Incomplete

def eigenvector_centrality(
    G: Incomplete,
    max_iter: int = ...,
    tol: float = ...,
    nstart: Incomplete | None = ...,
    weight: Incomplete | None = ...,
) -> Incomplete: ...
def eigenvector_centrality_numpy(
    G: Incomplete, weight: Incomplete | None = ..., max_iter: int = ..., tol: int = ...
) -> Incomplete: ...
