# Stubs for networkx.algorithms.centrality.eigenvector (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any
from _typeshed import Incomplete

def eigenvector_centrality(
    G: Any,
    max_iter: int = ...,
    tol: float = ...,
    nstart: Any | None = ...,
    weight: Any | None = ...,
) -> Incomplete: ...
def eigenvector_centrality_numpy(
    G: Any, weight: Any | None = ..., max_iter: int = ..., tol: int = ...
) -> Incomplete: ...
