# Stubs for networkx.algorithms.centrality.harmonic (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

def harmonic_centrality(G: Any, nbunch: Any | None = ..., distance: Any | None = ...) -> Any: ...
