# Stubs for networkx.algorithms.centrality.harmonic (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from _typeshed import Incomplete

def harmonic_centrality(
    G: Incomplete, nbunch: Incomplete | None = ..., distance: Incomplete | None = ...
) -> Incomplete: ...
