# Stubs for networkx.algorithms.centrality.katz (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any
from _typeshed import Incomplete

def katz_centrality(
    G: Any,
    alpha: float = ...,
    beta: float = ...,
    max_iter: int = ...,
    tol: float = ...,
    nstart: Any | None = ...,
    normalized: bool = ...,
    weight: Any | None = ...,
) -> Incomplete: ...
def katz_centrality_numpy(
    G: Any,
    alpha: float = ...,
    beta: float = ...,
    normalized: bool = ...,
    weight: Any | None = ...,
) -> Incomplete: ...
