# Stubs for networkx.algorithms.centrality.load (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from _typeshed import Incomplete

# load_centrality = newman_betweenness_centrality

def edge_load_centrality(G: Incomplete, cutoff: bool = ...) -> Incomplete: ...
