# Stubs for networkx.algorithms.centrality.percolation (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

def percolation_centrality(G: Any, attribute: str = ..., states: Any | None = ..., weight: Any | None = ...) -> Any: ...
