# Stubs for networkx.algorithms.centrality.reaching (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any
from _typeshed import Incomplete

def global_reaching_centrality(
    G: Any, weight: Any | None = ..., normalized: bool = ...
) -> Incomplete: ...
def local_reaching_centrality(
    G: Any,
    v: Any,
    paths: Any | None = ...,
    weight: Any | None = ...,
    normalized: bool = ...,
) -> Incomplete: ...
