# Stubs for networkx.algorithms.centrality.reaching (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from _typeshed import Incomplete

def global_reaching_centrality(
    G: Incomplete, weight: Incomplete | None = ..., normalized: bool = ...
) -> Incomplete: ...
def local_reaching_centrality(
    G: Incomplete,
    v: Incomplete,
    paths: Incomplete | None = ...,
    weight: Incomplete | None = ...,
    normalized: bool = ...,
) -> Incomplete: ...
