# Stubs for networkx.algorithms.centrality.second_order (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any
from _typeshed import Incomplete

def second_order_centrality(G: Any) -> Incomplete: ...
