# Stubs for networkx.algorithms.centrality.second_order (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from _typeshed import Incomplete

def second_order_centrality(G: Incomplete) -> Incomplete: ...
