# Stubs for networkx.algorithms.centrality.voterank_alg (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

def voterank(G: Any, number_of_nodes: Any | None = ..., max_iter: int = ...) -> Any: ...
