# Stubs for networkx.algorithms.centrality.voterank_alg (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from _typeshed import Incomplete

def voterank(
    G: Incomplete, number_of_nodes: Incomplete | None = ..., max_iter: int = ...
) -> Incomplete: ...
