# Stubs for networkx.utils.contextmanagers (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from _typeshed import Incomplete

def reversed(G: Incomplete) -> None: ...
