# Stubs for networkx.utils.rcm (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

def cuthill_mckee_ordering(G: Any, heuristic: Any | None = ...) -> None: ...
def reverse_cuthill_mckee_ordering(G: Any, heuristic: Any | None = ...) -> Any: ...
