# Stubs for networkx.algorithms.components.semiconnected (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any
from _typeshed import Incomplete

def is_semiconnected(G: Any) -> Incomplete: ...
