# Stubs for networkx.algorithms.components.semiconnected (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from _typeshed import Incomplete

def is_semiconnected(G: Incomplete) -> Incomplete: ...
