# Stubs for networkx.algorithms.operators.unary (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

def complement(G: Any): ...
def reverse(G: Any, copy: bool = ...): ...
