# Stubs for networkx.algorithms.operators.unary (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any, TypeVar

from networkx.classes.digraph import DiGraph

_T = TypeVar("_T")

def complement(G: Any) -> Any: ...
def reverse(G: DiGraph[_T], copy: bool = ...) -> DiGraph[_T]: ...
