# Stubs for networkx.algorithms.isomorphism.isomorph (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

def could_be_isomorphic(G1: Any, G2: Any) -> Any: ...

graph_could_be_isomorphic = could_be_isomorphic

def fast_could_be_isomorphic(G1: Any, G2: Any) -> Any: ...

fast_graph_could_be_isomorphic = fast_could_be_isomorphic

def faster_could_be_isomorphic(G1: Any, G2: Any) -> Any: ...

faster_graph_could_be_isomorphic = faster_could_be_isomorphic

def is_isomorphic(G1: Any, G2: Any, node_match: Any | None = ..., edge_match: Any | None = ...) -> Any: ...
