# Stubs for networkx.algorithms.isomorphism.isomorph (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from _typeshed import Incomplete

def could_be_isomorphic(G1: Incomplete, G2: Incomplete) -> Incomplete: ...

graph_could_be_isomorphic = could_be_isomorphic

def fast_could_be_isomorphic(G1: Incomplete, G2: Incomplete) -> Incomplete: ...

fast_graph_could_be_isomorphic = fast_could_be_isomorphic

def faster_could_be_isomorphic(G1: Incomplete, G2: Incomplete) -> Incomplete: ...

faster_graph_could_be_isomorphic = faster_could_be_isomorphic

def is_isomorphic(
    G1: Incomplete,
    G2: Incomplete,
    node_match: Incomplete | None = ...,
    edge_match: Incomplete | None = ...,
) -> Incomplete: ...
