# Stubs for networkx.algorithms.isomorphism.matchhelpers (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from _typeshed import Incomplete

def categorical_node_match(attr: Incomplete, default: Incomplete) -> Incomplete: ...

categorical_edge_match: Incomplete

def categorical_multiedge_match(
    attr: Incomplete, default: Incomplete
) -> Incomplete: ...
def numerical_node_match(
    attr: Incomplete, default: Incomplete, rtol: float = ..., atol: float = ...
) -> Incomplete: ...

numerical_edge_match: Incomplete

def numerical_multiedge_match(
    attr: Incomplete, default: Incomplete, rtol: float = ..., atol: float = ...
) -> Incomplete: ...
def generic_node_match(
    attr: Incomplete, default: Incomplete, op: Incomplete
) -> Incomplete: ...

generic_edge_match: Incomplete

def generic_multiedge_match(
    attr: Incomplete, default: Incomplete, op: Incomplete
) -> Incomplete: ...
