# Stubs for networkx.algorithms.isomorphism.matchhelpers (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

def categorical_node_match(attr: Any, default: Any) -> Any: ...

categorical_edge_match: Any

def categorical_multiedge_match(attr: Any, default: Any) -> Any: ...
def numerical_node_match(attr: Any, default: Any, rtol: float = ..., atol: float = ...) -> Any: ...

numerical_edge_match: Any

def numerical_multiedge_match(attr: Any, default: Any, rtol: float = ..., atol: float = ...) -> Any: ...
def generic_node_match(attr: Any, default: Any, op: Any) -> Any: ...

generic_edge_match: Any

def generic_multiedge_match(attr: Any, default: Any, op: Any) -> Any: ...
