# Stubs for networkx.drawing.nx_pylab (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from _typeshed import Incomplete

def draw(
    G: Incomplete,
    pos: Incomplete | None = ...,
    ax: Incomplete | None = ...,
    **kwds: Incomplete,
) -> None: ...
def draw_networkx(
    G: Incomplete,
    pos: Incomplete | None = ...,
    arrows: bool = ...,
    with_labels: bool = ...,
    **kwds: Incomplete,
) -> None: ...
def draw_networkx_nodes(
    G: Incomplete,
    pos: Incomplete,
    nodelist: Incomplete | None = ...,
    node_size: int = ...,
    node_color: str = ...,
    node_shape: str = ...,
    alpha: float = ...,
    cmap: Incomplete | None = ...,
    vmin: Incomplete | None = ...,
    vmax: Incomplete | None = ...,
    ax: Incomplete | None = ...,
    linewidths: Incomplete | None = ...,
    edgecolors: Incomplete | None = ...,
    label: Incomplete | None = ...,
    **kwds: Incomplete,
) -> Incomplete: ...
def draw_networkx_edges(
    G: Incomplete,
    pos: Incomplete,
    edgelist: Incomplete | None = ...,
    width: float = ...,
    edge_color: str = ...,
    style: str = ...,
    alpha: float = ...,
    arrowstyle: str = ...,
    arrowsize: int = ...,
    edge_cmap: Incomplete | None = ...,
    edge_vmin: Incomplete | None = ...,
    edge_vmax: Incomplete | None = ...,
    ax: Incomplete | None = ...,
    arrows: bool = ...,
    label: Incomplete | None = ...,
    node_size: int = ...,
    nodelist: Incomplete | None = ...,
    node_shape: str = ...,
    connectionstyle: Incomplete | None = ...,
    **kwds: Incomplete,
) -> Incomplete: ...
def draw_networkx_labels(
    G: Incomplete,
    pos: Incomplete,
    labels: Incomplete | None = ...,
    font_size: int = ...,
    font_color: str = ...,
    font_family: str = ...,
    font_weight: str = ...,
    alpha: float = ...,
    bbox: Incomplete | None = ...,
    ax: Incomplete | None = ...,
    **kwds: Incomplete,
) -> Incomplete: ...
def draw_networkx_edge_labels(
    G: Incomplete,
    pos: Incomplete,
    edge_labels: Incomplete | None = ...,
    label_pos: float = ...,
    font_size: int = ...,
    font_color: str = ...,
    font_family: str = ...,
    font_weight: str = ...,
    alpha: float = ...,
    bbox: Incomplete | None = ...,
    ax: Incomplete | None = ...,
    rotate: bool = ...,
    **kwds: Incomplete,
) -> Incomplete: ...
def draw_circular(G: Incomplete, **kwargs: Incomplete) -> None: ...
def draw_kamada_kawai(G: Incomplete, **kwargs: Incomplete) -> None: ...
def draw_random(G: Incomplete, **kwargs: Incomplete) -> None: ...
def draw_spectral(G: Incomplete, **kwargs: Incomplete) -> None: ...
def draw_spring(G: Incomplete, **kwargs: Incomplete) -> None: ...
def draw_shell(G: Incomplete, **kwargs: Incomplete) -> None: ...
def draw_planar(G: Incomplete, **kwargs: Incomplete) -> None: ...
