# Stubs for networkx.algorithms.boundary (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

def edge_boundary(
    G: Any, nbunch1: Any, nbunch2: Any | None = ..., data: bool = ..., keys: bool = ..., default: Any | None = ...
): ...
def node_boundary(G: Any, nbunch1: Any, nbunch2: Any | None = ...): ...
