# Stubs for networkx.algorithms.chains (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

def chain_decomposition(G: Any, root: Any | None = ...): ...
