from typing import Any

def triangles(G: Any, nodes: Any | None = ...) -> Any: ...
def average_clustering(G: Any, nodes: Any | None = ..., weight: Any | None = ..., count_zeros: bool = ...) -> Any: ...
def clustering(G: Any, nodes: Any | None = ..., weight: Any | None = ...) -> Any: ...
def transitivity(G: Any) -> Any: ...
def square_clustering(G: Any, nodes: Any | None = ...) -> Any: ...
def generalized_degree(G: Any, nodes: Any | None = ...) -> Any: ...
