from typing import Any
from _typeshed import Incomplete

def triangles(G: Any, nodes: Any | None = ...) -> Incomplete: ...
def average_clustering(
    G: Any, nodes: Any | None = ..., weight: Any | None = ..., count_zeros: bool = ...
) -> Incomplete: ...
def clustering(
    G: Any, nodes: Any | None = ..., weight: Any | None = ...
) -> Incomplete: ...
def transitivity(G: Any) -> Incomplete: ...
def square_clustering(G: Any, nodes: Any | None = ...) -> Incomplete: ...
def generalized_degree(G: Any, nodes: Any | None = ...) -> Incomplete: ...
