from _typeshed import Incomplete

def triangles(G: Incomplete, nodes: Incomplete | None = ...) -> Incomplete: ...
def average_clustering(
    G: Incomplete,
    nodes: Incomplete | None = ...,
    weight: Incomplete | None = ...,
    count_zeros: bool = ...,
) -> Incomplete: ...
def clustering(
    G: Incomplete, nodes: Incomplete | None = ..., weight: Incomplete | None = ...
) -> Incomplete: ...
def transitivity(G: Incomplete) -> Incomplete: ...
def square_clustering(G: Incomplete, nodes: Incomplete | None = ...) -> Incomplete: ...
def generalized_degree(G: Incomplete, nodes: Incomplete | None = ...) -> Incomplete: ...
