# Stubs for networkx.algorithms.communicability_alg (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from _typeshed import Incomplete
from networkx.utils import *

def communicability(G: Incomplete) -> Incomplete: ...
def communicability_exp(G: Incomplete) -> Incomplete: ...
