# Stubs for networkx.algorithms.communicability_alg (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any
from _typeshed import Incomplete

from networkx.utils import *

def communicability(G: Any) -> Incomplete: ...
def communicability_exp(G: Any) -> Incomplete: ...
