# Stubs for networkx.algorithms.communicability_alg (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

from networkx.utils import *

def communicability(G: Any) -> Any: ...
def communicability_exp(G: Any) -> Any: ...
