# Stubs for networkx.algorithms.cuts (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from _typeshed import Incomplete

def cut_size(
    G: Incomplete,
    S: Incomplete,
    T: Incomplete | None = ...,
    weight: Incomplete | None = ...,
) -> Incomplete: ...
def volume(
    G: Incomplete, S: Incomplete, weight: Incomplete | None = ...
) -> Incomplete: ...
def normalized_cut_size(
    G: Incomplete,
    S: Incomplete,
    T: Incomplete | None = ...,
    weight: Incomplete | None = ...,
) -> Incomplete: ...
def conductance(
    G: Incomplete,
    S: Incomplete,
    T: Incomplete | None = ...,
    weight: Incomplete | None = ...,
) -> Incomplete: ...
def edge_expansion(
    G: Incomplete,
    S: Incomplete,
    T: Incomplete | None = ...,
    weight: Incomplete | None = ...,
) -> Incomplete: ...
def mixing_expansion(
    G: Incomplete,
    S: Incomplete,
    T: Incomplete | None = ...,
    weight: Incomplete | None = ...,
) -> Incomplete: ...
def node_expansion(G: Incomplete, S: Incomplete) -> Incomplete: ...
def boundary_expansion(G: Incomplete, S: Incomplete) -> Incomplete: ...
