# Stubs for networkx.algorithms.dominance (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from _typeshed import Incomplete

def immediate_dominators(G: Incomplete, start: Incomplete) -> Incomplete: ...
def dominance_frontiers(G: Incomplete, start: Incomplete) -> Incomplete: ...
