# Stubs for networkx.algorithms.dominance (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

def immediate_dominators(G: Any, start: Any) -> Any: ...
def dominance_frontiers(G: Any, start: Any) -> Any: ...
