# Stubs for networkx.algorithms.dominating (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

def dominating_set(G: Any, start_with: Any | None = ...) -> Incomplete: ...
def is_dominating_set(G: Any, nbunch: Any) -> Incomplete: ...
