# Stubs for networkx.algorithms.dominating (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from _typeshed import Incomplete

def dominating_set(
    G: Incomplete, start_with: Incomplete | None = ...
) -> Incomplete: ...
def is_dominating_set(G: Incomplete, nbunch: Incomplete) -> Incomplete: ...
