# Stubs for networkx.algorithms.efficiency (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any
from _typeshed import Incomplete

def efficiency(G: Any, u: Any, v: Any) -> Incomplete: ...
def global_efficiency(G: Any) -> Incomplete: ...
def local_efficiency(G: Any) -> Incomplete: ...
