# Stubs for networkx.algorithms.hierarchy (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

def flow_hierarchy(G: Any, weight: Any | None = ...) -> Any: ...
