# Stubs for networkx.algorithms.hierarchy (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from _typeshed import Incomplete

def flow_hierarchy(G: Incomplete, weight: Incomplete | None = ...) -> Incomplete: ...
