# Stubs for networkx.algorithms.hybrid (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from _typeshed import Incomplete

def kl_connected_subgraph(
    G: Incomplete,
    k: Incomplete,
    l: Incomplete,
    low_memory: bool = ...,
    same_as_graph: bool = ...,
) -> Incomplete: ...
def is_kl_connected(
    G: Incomplete, k: Incomplete, l: Incomplete, low_memory: bool = ...
) -> Incomplete: ...
