# Stubs for networkx.algorithms.isolate (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any
from _typeshed import Incomplete

def is_isolate(G: Any, n: Any) -> Incomplete: ...
def isolates(G: Any) -> Incomplete: ...
def number_of_isolates(G: Any) -> Incomplete: ...
