# Stubs for networkx.algorithms.lowest_common_ancestors (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from _typeshed import Incomplete

def tree_all_pairs_lowest_common_ancestor(
    G: Incomplete, root: Incomplete | None = ..., pairs: Incomplete | None = ...
) -> None: ...
def lowest_common_ancestor(
    G: Incomplete,
    node1: Incomplete,
    node2: Incomplete,
    default: Incomplete | None = ...,
) -> Incomplete: ...
def all_pairs_lowest_common_ancestor(
    G: Incomplete, pairs: Incomplete | None = ...
) -> Incomplete: ...
