# Stubs for networkx.algorithms.minors (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from _typeshed import Incomplete

def quotient_graph(
    G: Incomplete,
    partition: Incomplete,
    edge_relation: Incomplete | None = ...,
    node_data: Incomplete | None = ...,
    edge_data: Incomplete | None = ...,
    relabel: bool = ...,
    create_using: Incomplete | None = ...,
) -> Incomplete: ...
def contracted_nodes(
    G: Incomplete, u: Incomplete, v: Incomplete, self_loops: bool = ...
) -> Incomplete: ...

identified_nodes = contracted_nodes

def contracted_edge(
    G: Incomplete, edge: Incomplete, self_loops: bool = ...
) -> Incomplete: ...
