# Stubs for networkx.algorithms.minors (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any
from _typeshed import Incomplete

def quotient_graph(
    G: Any,
    partition: Any,
    edge_relation: Any | None = ...,
    node_data: Any | None = ...,
    edge_data: Any | None = ...,
    relabel: bool = ...,
    create_using: Any | None = ...,
) -> Incomplete: ...
def contracted_nodes(G: Any, u: Any, v: Any, self_loops: bool = ...) -> Incomplete: ...

identified_nodes = contracted_nodes

def contracted_edge(G: Any, edge: Any, self_loops: bool = ...) -> Incomplete: ...
