# Stubs for networkx.algorithms.mis (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from _typeshed import Incomplete

def maximal_independent_set(
    G: Incomplete, nodes: Incomplete | None = ..., seed: Incomplete | None = ...
) -> Incomplete: ...
