# Stubs for networkx.algorithms.mis (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

def maximal_independent_set(G: Any, nodes: Any | None = ..., seed: Any | None = ...) -> Any: ...
