# Stubs for networkx.algorithms.moral (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any
from _typeshed import Incomplete

def moral_graph(G: Any) -> Incomplete: ...
