# Stubs for networkx.algorithms.planar_drawing (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from _typeshed import Incomplete

def combinatorial_embedding_to_pos(
    embedding: Incomplete, fully_triangulate: bool = ...
) -> Incomplete: ...
