# Stubs for networkx.algorithms.reciprocity (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from _typeshed import Incomplete

def reciprocity(G: Incomplete, nodes: Incomplete | None = ...) -> Incomplete: ...
def overall_reciprocity(G: Incomplete) -> Incomplete: ...
