# Stubs for networkx.algorithms.reciprocity (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

def reciprocity(G: Any, nodes: Any | None = ...) -> Any: ...
def overall_reciprocity(G: Any) -> Any: ...
