# Stubs for networkx.algorithms.richclub (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

def rich_club_coefficient(G: Any, normalized: bool = ..., Q: int = ..., seed: Any | None = ...) -> Any: ...
