# Stubs for networkx.algorithms.smallworld (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from _typeshed import Incomplete

def random_reference(
    G: Incomplete,
    niter: int = ...,
    connectivity: bool = ...,
    seed: Incomplete | None = ...,
) -> Incomplete: ...
def lattice_reference(
    G: Incomplete,
    niter: int = ...,
    D: Incomplete | None = ...,
    connectivity: bool = ...,
    seed: Incomplete | None = ...,
) -> Incomplete: ...
def sigma(
    G: Incomplete, niter: int = ..., nrand: int = ..., seed: Incomplete | None = ...
) -> Incomplete: ...
def omega(
    G: Incomplete, niter: int = ..., nrand: int = ..., seed: Incomplete | None = ...
) -> Incomplete: ...
