# Stubs for networkx.algorithms.smetric (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from _typeshed import Incomplete

def s_metric(G: Incomplete, normalized: bool = ...) -> Incomplete: ...
