# Stubs for networkx.algorithms.smetric (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any
from _typeshed import Incomplete

def s_metric(G: Any, normalized: bool = ...) -> Incomplete: ...
