# Stubs for networkx.algorithms.sparsifiers (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

def spanner(G: Any, stretch: Any, weight: Any | None = ..., seed: Any | None = ...) -> Any: ...
