# Stubs for networkx.algorithms.sparsifiers (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any
from _typeshed import Incomplete

def spanner(
    G: Any, stretch: Any, weight: Any | None = ..., seed: Any | None = ...
) -> Incomplete: ...
