# Stubs for networkx.algorithms.sparsifiers (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from _typeshed import Incomplete

def spanner(
    G: Incomplete,
    stretch: Incomplete,
    weight: Incomplete | None = ...,
    seed: Incomplete | None = ...,
) -> Incomplete: ...
