# Stubs for networkx.algorithms.swap (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

def double_edge_swap(G: Any, nswap: int = ..., max_tries: int = ..., seed: Any | None = ...) -> Any: ...
def connected_double_edge_swap(G: Any, nswap: int = ..., _window_threshold: int = ..., seed: Any | None = ...) -> Any: ...
