# Stubs for networkx.algorithms.threshold (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

def is_threshold_graph(G: Any) -> Any: ...
def find_threshold_graph(G: Any, create_using: Any | None = ...) -> Any: ...
