# Stubs for networkx.algorithms.triads (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any
from _typeshed import Incomplete

def triadic_census(G: Any) -> Incomplete: ...
