# Stubs for networkx.algorithms.vitality (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

def closeness_vitality(G: Any, node: Any | None = ..., weight: Any | None = ..., wiener_index: Any | None = ...) -> Any: ...
