# Stubs for networkx.algorithms.vitality (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any
from _typeshed import Incomplete

def closeness_vitality(
    G: Any,
    node: Any | None = ...,
    weight: Any | None = ...,
    wiener_index: Any | None = ...,
) -> Incomplete: ...
