# Stubs for networkx.algorithms.voronoi (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any
from _typeshed import Incomplete

def voronoi_cells(G: Any, center_nodes: Any, weight: str = ...) -> Incomplete: ...
