# Stubs for networkx.algorithms.voronoi (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from _typeshed import Incomplete

def voronoi_cells(
    G: Incomplete, center_nodes: Incomplete, weight: str = ...
) -> Incomplete: ...
