# Stubs for networkx.algorithms.wiener (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any
from _typeshed import Incomplete

def wiener_index(G: Any, weight: Any | None = ...) -> Incomplete: ...
