# Stubs for networkx.algorithms.wiener (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from _typeshed import Incomplete

def wiener_index(G: Incomplete, weight: Incomplete | None = ...) -> Incomplete: ...
