# Stubs for networkx.algorithms.assortativity.connectivity (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from _typeshed import Incomplete

def average_degree_connectivity(
    G: Incomplete,
    source: str = ...,
    target: str = ...,
    nodes: Incomplete | None = ...,
    weight: Incomplete | None = ...,
) -> None: ...
