# Stubs for networkx.algorithms.assortativity.connectivity (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

def average_degree_connectivity(
    G: Any, source: str = ..., target: str = ..., nodes: Any | None = ..., weight: Any | None = ...
) -> None: ...
