# Stubs for networkx.algorithms.assortativity.correlation (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

def degree_assortativity_coefficient(
    G: Any,
    x: str = ...,
    y: str = ...,
    weight: Any | None = ...,
    nodes: Any | None = ...,
) -> Incomplete: ...
def degree_pearson_correlation_coefficient(
    G: Any,
    x: str = ...,
    y: str = ...,
    weight: Any | None = ...,
    nodes: Any | None = ...,
) -> Incomplete: ...
def attribute_assortativity_coefficient(
    G: Any, attribute: Any, nodes: Any | None = ...
) -> Incomplete: ...
def numeric_assortativity_coefficient(
    G: Any, attribute: Any, nodes: Any | None = ...
) -> Incomplete: ...
