# Stubs for networkx.algorithms.assortativity.correlation (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from _typeshed import Incomplete

def degree_assortativity_coefficient(
    G: Incomplete,
    x: str = ...,
    y: str = ...,
    weight: Incomplete | None = ...,
    nodes: Incomplete | None = ...,
) -> Incomplete: ...
def degree_pearson_correlation_coefficient(
    G: Incomplete,
    x: str = ...,
    y: str = ...,
    weight: Incomplete | None = ...,
    nodes: Incomplete | None = ...,
) -> Incomplete: ...
def attribute_assortativity_coefficient(
    G: Incomplete, attribute: Incomplete, nodes: Incomplete | None = ...
) -> Incomplete: ...
def numeric_assortativity_coefficient(
    G: Incomplete, attribute: Incomplete, nodes: Incomplete | None = ...
) -> Incomplete: ...
