# Stubs for networkx.algorithms.assortativity.mixing (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from _typeshed import Incomplete

def attribute_mixing_dict(
    G: Incomplete,
    attribute: Incomplete,
    nodes: Incomplete | None = ...,
    normalized: bool = ...,
) -> Incomplete: ...
def attribute_mixing_matrix(
    G: Incomplete,
    attribute: Incomplete,
    nodes: Incomplete | None = ...,
    mapping: Incomplete | None = ...,
    normalized: bool = ...,
) -> Incomplete: ...
def degree_mixing_dict(
    G: Incomplete,
    x: str = ...,
    y: str = ...,
    weight: Incomplete | None = ...,
    nodes: Incomplete | None = ...,
    normalized: bool = ...,
) -> Incomplete: ...
def degree_mixing_matrix(
    G: Incomplete,
    x: str = ...,
    y: str = ...,
    weight: Incomplete | None = ...,
    nodes: Incomplete | None = ...,
    normalized: bool = ...,
) -> Incomplete: ...
def numeric_mixing_matrix(
    G: Incomplete,
    attribute: Incomplete,
    nodes: Incomplete | None = ...,
    normalized: bool = ...,
) -> Incomplete: ...
def mixing_dict(xy: Incomplete, normalized: bool = ...) -> Incomplete: ...
