# Stubs for networkx.algorithms.assortativity.mixing (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any
from _typeshed import Incomplete

def attribute_mixing_dict(
    G: Any, attribute: Any, nodes: Any | None = ..., normalized: bool = ...
) -> Incomplete: ...
def attribute_mixing_matrix(
    G: Any,
    attribute: Any,
    nodes: Any | None = ...,
    mapping: Any | None = ...,
    normalized: bool = ...,
) -> Incomplete: ...
def degree_mixing_dict(
    G: Any,
    x: str = ...,
    y: str = ...,
    weight: Any | None = ...,
    nodes: Any | None = ...,
    normalized: bool = ...,
) -> Incomplete: ...
def degree_mixing_matrix(
    G: Any,
    x: str = ...,
    y: str = ...,
    weight: Any | None = ...,
    nodes: Any | None = ...,
    normalized: bool = ...,
) -> Incomplete: ...
def numeric_mixing_matrix(
    G: Any, attribute: Any, nodes: Any | None = ..., normalized: bool = ...
) -> Incomplete: ...
def mixing_dict(xy: Any, normalized: bool = ...) -> Incomplete: ...
