# Stubs for networkx.algorithms.assortativity.neighbor_degree (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from _typeshed import Incomplete

def average_neighbor_degree(
    G: Incomplete,
    source: str = ...,
    target: str = ...,
    nodes: Incomplete | None = ...,
    weight: Incomplete | None = ...,
) -> Incomplete: ...
