# Stubs for networkx.algorithms.assortativity.neighbor_degree (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

def average_neighbor_degree(
    G: Any,
    source: str = ...,
    target: str = ...,
    nodes: Any | None = ...,
    weight: Any | None = ...,
) -> Any: ...
