# Stubs for networkx.algorithms.assortativity.pairs (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from _typeshed import Incomplete

def node_attribute_xy(
    G: Incomplete, attribute: Incomplete, nodes: Incomplete | None = ...
) -> None: ...
def node_degree_xy(
    G: Incomplete,
    x: str = ...,
    y: str = ...,
    weight: Incomplete | None = ...,
    nodes: Incomplete | None = ...,
) -> None: ...
