# Stubs for networkx.linalg.algebraicconnectivity (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from _typeshed import Incomplete
from numpy import dot  # type: ignore

ddot = dot

class _PCGSolver:
    def __init__(self, A: Incomplete, M: Incomplete) -> None: ...
    def solve(self, B: Incomplete, tol: Incomplete) -> Incomplete: ...

class _CholeskySolver:
    def __init__(self, A: Incomplete) -> None: ...
    def solve(self, B: Incomplete, tol: Incomplete | None = ...) -> Incomplete: ...

class _LUSolver:
    def __init__(self, A: Incomplete) -> None: ...
    def solve(self, B: Incomplete, tol: Incomplete | None = ...) -> Incomplete: ...

def algebraic_connectivity(
    G: Incomplete,
    weight: str = ...,
    normalized: bool = ...,
    tol: float = ...,
    method: str = ...,
    seed: Incomplete | None = ...,
) -> Incomplete: ...
def fiedler_vector(
    G: Incomplete,
    weight: str = ...,
    normalized: bool = ...,
    tol: float = ...,
    method: str = ...,
    seed: Incomplete | None = ...,
) -> Incomplete: ...
def spectral_ordering(
    G: Incomplete,
    weight: str = ...,
    normalized: bool = ...,
    tol: float = ...,
    method: str = ...,
    seed: Incomplete | None = ...,
) -> Incomplete: ...
def setup_module(module: Incomplete) -> None: ...
