# Stubs for networkx.linalg.attrmatrix (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from _typeshed import Incomplete

def attr_matrix(
    G: Incomplete,
    edge_attr: Incomplete | None = ...,
    node_attr: Incomplete | None = ...,
    normalized: bool = ...,
    rc_order: Incomplete | None = ...,
    dtype: Incomplete | None = ...,
    order: Incomplete | None = ...,
) -> Incomplete: ...
def attr_sparse_matrix(
    G: Incomplete,
    edge_attr: Incomplete | None = ...,
    node_attr: Incomplete | None = ...,
    normalized: bool = ...,
    rc_order: Incomplete | None = ...,
    dtype: Incomplete | None = ...,
) -> Incomplete: ...
