# Stubs for networkx.linalg.attrmatrix (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

def attr_matrix(
    G: Any,
    edge_attr: Any | None = ...,
    node_attr: Any | None = ...,
    normalized: bool = ...,
    rc_order: Any | None = ...,
    dtype: Any | None = ...,
    order: Any | None = ...,
) -> Any: ...
def attr_sparse_matrix(
    G: Any,
    edge_attr: Any | None = ...,
    node_attr: Any | None = ...,
    normalized: bool = ...,
    rc_order: Any | None = ...,
    dtype: Any | None = ...,
) -> Any: ...
