# Stubs for networkx.linalg.graphmatrix (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from _typeshed import Incomplete

def incidence_matrix(
    G: Incomplete,
    nodelist: Incomplete | None = ...,
    edgelist: Incomplete | None = ...,
    oriented: bool = ...,
    weight: Incomplete | None = ...,
) -> Incomplete: ...
def adjacency_matrix(
    G: Incomplete, nodelist: Incomplete | None = ..., weight: str = ...
) -> Incomplete: ...

adj_matrix = adjacency_matrix
