# Stubs for networkx.linalg.graphmatrix (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

def incidence_matrix(
    G: Any, nodelist: Any | None = ..., edgelist: Any | None = ..., oriented: bool = ..., weight: Any | None = ...
) -> Any: ...
def adjacency_matrix(G: Any, nodelist: Any | None = ..., weight: str = ...) -> Any: ...

adj_matrix = adjacency_matrix
