# Stubs for networkx.linalg.laplacianmatrix (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

def laplacian_matrix(G: Any, nodelist: Any | None = ..., weight: str = ...) -> Incomplete: ...
def normalized_laplacian_matrix(
    G: Any, nodelist: Any | None = ..., weight: str = ...
) -> Incomplete: ...
def directed_laplacian_matrix(
    G: Any,
    nodelist: Any | None = ...,
    weight: str = ...,
    walk_type: Any | None = ...,
    alpha: float = ...,
) -> Incomplete: ...
def directed_combinatorial_laplacian_matrix(
    G: Any,
    nodelist: Any | None = ...,
    weight: str = ...,
    walk_type: Any | None = ...,
    alpha: float = ...,
) -> Incomplete: ...
