# Stubs for networkx.linalg.laplacianmatrix (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from _typeshed import Incomplete

def laplacian_matrix(
    G: Incomplete, nodelist: Incomplete | None = ..., weight: str = ...
) -> Incomplete: ...
def normalized_laplacian_matrix(
    G: Incomplete, nodelist: Incomplete | None = ..., weight: str = ...
) -> Incomplete: ...
def directed_laplacian_matrix(
    G: Incomplete,
    nodelist: Incomplete | None = ...,
    weight: str = ...,
    walk_type: Incomplete | None = ...,
    alpha: float = ...,
) -> Incomplete: ...
def directed_combinatorial_laplacian_matrix(
    G: Incomplete,
    nodelist: Incomplete | None = ...,
    weight: str = ...,
    walk_type: Incomplete | None = ...,
    alpha: float = ...,
) -> Incomplete: ...
