# Stubs for networkx.linalg.modularitymatrix (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

def modularity_matrix(G: Any, nodelist: Any | None = ..., weight: Any | None = ...) -> Any: ...
def directed_modularity_matrix(G: Any, nodelist: Any | None = ..., weight: Any | None = ...) -> Any: ...
