# Stubs for networkx.algorithms.coloring.equitable_coloring (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from _typeshed import Incomplete

def equitable_color(G: Incomplete, num_colors: Incomplete) -> Incomplete: ...
