# Stubs for networkx.algorithms.coloring.equitable_coloring (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any
from _typeshed import Incomplete

def equitable_color(G: Any, num_colors: Any) -> Incomplete: ...
