# Stubs for networkx.classes (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from .digraph import DiGraph as DiGraph
from .function import *
from .graph import Graph as Graph
from .multidigraph import MultiDiGraph as MultiDiGraph
from .multigraph import MultiGraph as MultiGraph
from .ordered import (
    OrderedDiGraph as OrderedDiGraph,
    OrderedGraph as OrderedGraph,
    OrderedMultiDiGraph as OrderedMultiDiGraph,
    OrderedMultiGraph as OrderedMultiGraph,
)
