# Stubs for networkx.classes (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from .digraph import DiGraph as DiGraph
from .function import *
from .graph import Graph as Graph
from .multidigraph import MultiDiGraph as MultiDiGraph
from .multigraph import MultiGraph as MultiGraph
from .ordered import OrderedDiGraph as OrderedDiGraph
from .ordered import OrderedGraph as OrderedGraph
from .ordered import OrderedMultiDiGraph as OrderedMultiDiGraph
from .ordered import OrderedMultiGraph as OrderedMultiGraph
