# Stubs for networkx.classes.multigraph (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from networkx.classes.graph import Graph, Node, MapFactory

from typing import Optional, Generic, Dict

from networkx.classes.multidigraph import MultiDiGraph


class MultiGraph(Graph[Node], Generic[Node]):
    def new_edge_key(self, u: Node, v: Node) -> int: ...
    def copy(self, as_view: bool = ...) -> MultiGraph[Node]: ...
    def to_directed(self, as_view: bool = ...) -> MultiDiGraph[Node]: ...
    def to_undirected(self, as_view: bool = ...) -> MultiGraph[Node]: ...
    def number_of_edges(self, u: Optional[Node] = ..., v: Optional[Node] = ...) -> int: ...
