# Stubs for networkx.classes.multidigraph (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from networkx.classes.digraph import DiGraph
from networkx.classes.graph import Node
from networkx.classes.multigraph import MultiGraph
from networkx.classes.reportviews import InMultiDegreeView, MultiDegreeView, OutMultiDegreeView

class MultiDiGraph(MultiGraph[Node], DiGraph[Node]):
    degree: MultiDegreeView[Node]
    in_degree: InMultiDegreeView[Node]
    out_degree: OutMultiDegreeView[Node]
    def to_undirected(self, reciprocal: bool = ..., as_view: bool = ...) -> MultiGraph[Node]: ...  # type: ignore
    def reverse(self, copy: bool = ...) -> MultiDiGraph[Node]: ...
    def copy(self, as_view: bool = ...) -> MultiDiGraph[Node]: ...
