# Stubs for networkx.classes.ordered (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from .digraph import DiGraph
from .graph import Graph, Node
from .multidigraph import MultiDiGraph
from .multigraph import MultiGraph
from typing import Any


class OrderedGraph(Graph[Node]):
    ...

class OrderedDiGraph(DiGraph[Node]):
    ...

class OrderedMultiGraph(MultiGraph[Node]):
    ...

class OrderedMultiDiGraph(MultiDiGraph[Node]):
    ...
