# Stubs for networkx.algorithms.node_classification.hmn (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from _typeshed import Incomplete

def harmonic_function(
    G: Incomplete, max_iter: int = ..., label_name: str = ...
) -> Incomplete: ...
