# Stubs for networkx.algorithms.node_classification.lgc (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from _typeshed import Incomplete

def local_and_global_consistency(
    G: Incomplete, alpha: float = ..., max_iter: int = ..., label_name: str = ...
) -> Incomplete: ...
