# Stubs for networkx.algorithms.community.centrality (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from _typeshed import Incomplete

def girvan_newman(
    G: Incomplete, most_valuable_edge: Incomplete | None = ...
) -> Incomplete: ...
