# Stubs for networkx.algorithms.community.community_utils (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from _typeshed import Incomplete

def is_partition(G: Incomplete, communities: Incomplete) -> Incomplete: ...
