# Stubs for networkx.algorithms.community.community_generators (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

def LFR_benchmark_graph(
    n: Any,
    tau1: Any,
    tau2: Any,
    mu: Any,
    average_degree: Any | None = ...,
    min_degree: Any | None = ...,
    max_degree: Any | None = ...,
    min_community: Any | None = ...,
    max_community: Any | None = ...,
    tol: float = ...,
    max_iters: int = ...,
    seed: Any | None = ...,
) -> Any: ...
