# Stubs for networkx.algorithms.community.community_generators (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from _typeshed import Incomplete

def LFR_benchmark_graph(
    n: Incomplete,
    tau1: Incomplete,
    tau2: Incomplete,
    mu: Incomplete,
    average_degree: Incomplete | None = ...,
    min_degree: Incomplete | None = ...,
    max_degree: Incomplete | None = ...,
    min_community: Incomplete | None = ...,
    max_community: Incomplete | None = ...,
    tol: float = ...,
    max_iters: int = ...,
    seed: Incomplete | None = ...,
) -> Incomplete: ...
