# Stubs for networkx.algorithms.community.community_utils (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any
from _typeshed import Incomplete

def is_partition(G: Any, communities: Any) -> Incomplete: ...
