# Stubs for networkx.algorithms.community.kclique (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from _typeshed import Incomplete

def k_clique_communities(
    G: Incomplete, k: Incomplete, cliques: Incomplete | None = ...
) -> None: ...
