# Stubs for networkx.algorithms.community.kclique (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

def k_clique_communities(G: Any, k: Any, cliques: Any | None = ...) -> None: ...
