# Stubs for networkx.algorithms.community.kernighan_lin (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from _typeshed import Incomplete

def kernighan_lin_bisection(
    G: Incomplete,
    partition: Incomplete | None = ...,
    max_iter: int = ...,
    weight: str = ...,
    seed: Incomplete | None = ...,
) -> Incomplete: ...
