# Stubs for networkx.algorithms.community.kernighan_lin (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

def kernighan_lin_bisection(
    G: Any, partition: Any | None = ..., max_iter: int = ..., weight: str = ..., seed: Any | None = ...
) -> Any: ...
