# Stubs for networkx.algorithms.community.label_propagation (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from _typeshed import Incomplete

def asyn_lpa_communities(
    G: Incomplete, weight: Incomplete | None = ..., seed: Incomplete | None = ...
) -> Incomplete: ...
def label_propagation_communities(G: Incomplete) -> None: ...
