# Stubs for networkx.algorithms.community.label_propagation (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

def asyn_lpa_communities(G: Any, weight: Any | None = ..., seed: Any | None = ...) -> Any: ...
def label_propagation_communities(G: Any) -> None: ...
