# Stubs for networkx.algorithms.community.label_propagation (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any
from _typeshed import Incomplete

def asyn_lpa_communities(
    G: Any, weight: Any | None = ..., seed: Any | None = ...
) -> Incomplete: ...
def label_propagation_communities(G: Any) -> None: ...
