# Stubs for networkx.algorithms.community.modularity_max (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any
from _typeshed import Incomplete

def greedy_modularity_communities(G: Any, weight: Any | None = ...) -> Incomplete: ...

# Names in __all__ with no definition:
#   _naive_greedy_modularity_communities
