# Stubs for networkx.algorithms.community.modularity_max (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from _typeshed import Incomplete

def greedy_modularity_communities(
    G: Incomplete, weight: Incomplete | None = ...
) -> Incomplete: ...

# Names in __all__ with no definition:
#   _naive_greedy_modularity_communities
