# Stubs for networkx.algorithms.link_analysis.pagerank_alg (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any
from _typeshed import Incomplete

def pagerank(
    G: Any,
    alpha: float = ...,
    personalization: Any | None = ...,
    max_iter: int = ...,
    tol: float = ...,
    nstart: Any | None = ...,
    weight: str = ...,
    dangling: Any | None = ...,
) -> Incomplete: ...
def google_matrix(
    G: Any,
    alpha: float = ...,
    personalization: Any | None = ...,
    nodelist: Any | None = ...,
    weight: str = ...,
    dangling: Any | None = ...,
) -> Incomplete: ...
def pagerank_numpy(
    G: Any,
    alpha: float = ...,
    personalization: Any | None = ...,
    weight: str = ...,
    dangling: Any | None = ...,
) -> Incomplete: ...
def pagerank_scipy(
    G: Any,
    alpha: float = ...,
    personalization: Any | None = ...,
    max_iter: int = ...,
    tol: float = ...,
    weight: str = ...,
    dangling: Any | None = ...,
) -> Incomplete: ...
