# Stubs for networkx.algorithms.link_analysis.pagerank_alg (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from _typeshed import Incomplete

def pagerank(
    G: Incomplete,
    alpha: float = ...,
    personalization: Incomplete | None = ...,
    max_iter: int = ...,
    tol: float = ...,
    nstart: Incomplete | None = ...,
    weight: str = ...,
    dangling: Incomplete | None = ...,
) -> Incomplete: ...
def google_matrix(
    G: Incomplete,
    alpha: float = ...,
    personalization: Incomplete | None = ...,
    nodelist: Incomplete | None = ...,
    weight: str = ...,
    dangling: Incomplete | None = ...,
) -> Incomplete: ...
def pagerank_numpy(
    G: Incomplete,
    alpha: float = ...,
    personalization: Incomplete | None = ...,
    weight: str = ...,
    dangling: Incomplete | None = ...,
) -> Incomplete: ...
def pagerank_scipy(
    G: Incomplete,
    alpha: float = ...,
    personalization: Incomplete | None = ...,
    max_iter: int = ...,
    tol: float = ...,
    weight: str = ...,
    dangling: Incomplete | None = ...,
) -> Incomplete: ...
