# Stubs for networkx.readwrite.adjlist (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

def generate_adjlist(G: Any, delimiter: str = ...) -> None: ...
def write_adjlist(G: Any, path: Any, comments: str = ..., delimiter: str = ..., encoding: str = ...) -> None: ...
def parse_adjlist(
    lines: Any, comments: str = ..., delimiter: Any | None = ..., create_using: Any | None = ..., nodetype: Any | None = ...
) -> Any: ...
def read_adjlist(
    path: Any,
    comments: str = ...,
    delimiter: Any | None = ...,
    create_using: Any | None = ...,
    nodetype: Any | None = ...,
    encoding: str = ...,
) -> Any: ...
