# Stubs for networkx.readwrite.edgelist (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

def generate_edgelist(G: Any, delimiter: str = ..., data: bool = ...) -> None: ...
def write_edgelist(
    G: Any, path: Any, comments: str = ..., delimiter: str = ..., data: bool = ..., encoding: str = ...
) -> None: ...
def parse_edgelist(
    lines: Any,
    comments: str = ...,
    delimiter: Any | None = ...,
    create_using: Any | None = ...,
    nodetype: Any | None = ...,
    data: bool = ...,
) -> Any: ...
def read_edgelist(
    path: Any,
    comments: str = ...,
    delimiter: Any | None = ...,
    create_using: Any | None = ...,
    nodetype: Any | None = ...,
    data: bool = ...,
    edgetype: Any | None = ...,
    encoding: str = ...,
) -> Any: ...
def write_weighted_edgelist(G: Any, path: Any, comments: str = ..., delimiter: str = ..., encoding: str = ...) -> None: ...
def read_weighted_edgelist(
    path: Any,
    comments: str = ...,
    delimiter: Any | None = ...,
    create_using: Any | None = ...,
    nodetype: Any | None = ...,
    encoding: str = ...,
) -> Any: ...
