# Stubs for networkx.readwrite.gml (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

long = int
unicode = str
unichr = chr

def read_gml(path: Any, label: str = ..., destringizer: Any | None = ...): ...
def parse_gml(lines: Any, label: str = ..., destringizer: Any | None = ...): ...
def generate_gml(G: Any, stringizer: Any | None = ...) -> None: ...
def write_gml(G: Any, path: Any, stringizer: Any | None = ...) -> None: ...
