# Stubs for networkx.readwrite.gpickle (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from _typeshed import Incomplete

def write_gpickle(
    G: Incomplete, path: Incomplete, protocol: Incomplete = ...
) -> None: ...
def read_gpickle(path: Incomplete) -> Incomplete: ...
