# Stubs for networkx.readwrite.leda (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any
from _typeshed import Incomplete

def read_leda(path: Any, encoding: str = ...) -> Incomplete: ...
def parse_leda(lines: Any) -> Incomplete: ...
