# Stubs for networkx.readwrite.leda (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from _typeshed import Incomplete

def read_leda(path: Incomplete, encoding: str = ...) -> Incomplete: ...
def parse_leda(lines: Incomplete) -> Incomplete: ...
