# Stubs for networkx.readwrite.multiline_adjlist (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from _typeshed import Incomplete

def generate_multiline_adjlist(G: Incomplete, delimiter: str = ...) -> None: ...
def write_multiline_adjlist(
    G: Incomplete,
    path: Incomplete,
    delimiter: str = ...,
    comments: str = ...,
    encoding: str = ...,
) -> None: ...
def parse_multiline_adjlist(
    lines: Incomplete,
    comments: str = ...,
    delimiter: Incomplete | None = ...,
    create_using: Incomplete | None = ...,
    nodetype: Incomplete | None = ...,
    edgetype: Incomplete | None = ...,
) -> Incomplete: ...
def read_multiline_adjlist(
    path: Incomplete,
    comments: str = ...,
    delimiter: Incomplete | None = ...,
    create_using: Incomplete | None = ...,
    nodetype: Incomplete | None = ...,
    edgetype: Incomplete | None = ...,
    encoding: str = ...,
) -> Incomplete: ...
