# Stubs for networkx.readwrite.nx_shp (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from _typeshed import Incomplete

def read_shp(
    path: Incomplete, simplify: bool = ..., geom_attrs: bool = ..., strict: bool = ...
) -> Incomplete: ...
def write_shp(G: Incomplete, outdir: Incomplete) -> Incomplete: ...
