# Stubs for networkx.readwrite.nx_yaml (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from _typeshed import Incomplete

def write_yaml(
    G_to_be_yaml: Incomplete, path_for_yaml_output: Incomplete, **kwds: Incomplete
) -> None: ...
def read_yaml(path: Incomplete) -> Incomplete: ...
