# Stubs for networkx.algorithms.connectivity.connectivity (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from _typeshed import Incomplete

def local_node_connectivity(
    G: Incomplete,
    s: Incomplete,
    t: Incomplete,
    flow_func: Incomplete | None = ...,
    auxiliary: Incomplete | None = ...,
    residual: Incomplete | None = ...,
    cutoff: Incomplete | None = ...,
) -> Incomplete: ...
def node_connectivity(
    G: Incomplete,
    s: Incomplete | None = ...,
    t: Incomplete | None = ...,
    flow_func: Incomplete | None = ...,
) -> Incomplete: ...
def average_node_connectivity(
    G: Incomplete, flow_func: Incomplete | None = ...
) -> Incomplete: ...
def all_pairs_node_connectivity(
    G: Incomplete, nbunch: Incomplete | None = ..., flow_func: Incomplete | None = ...
) -> Incomplete: ...
def local_edge_connectivity(
    G: Incomplete,
    s: Incomplete,
    t: Incomplete,
    flow_func: Incomplete | None = ...,
    auxiliary: Incomplete | None = ...,
    residual: Incomplete | None = ...,
    cutoff: Incomplete | None = ...,
) -> Incomplete: ...
def edge_connectivity(
    G: Incomplete,
    s: Incomplete | None = ...,
    t: Incomplete | None = ...,
    flow_func: Incomplete | None = ...,
    cutoff: Incomplete | None = ...,
) -> Incomplete: ...
