# Stubs for networkx.algorithms.connectivity.disjoint_paths (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

def edge_disjoint_paths(
    G: Any,
    s: Any,
    t: Any,
    flow_func: Any | None = ...,
    cutoff: Any | None = ...,
    auxiliary: Any | None = ...,
    residual: Any | None = ...,
) -> None: ...
def node_disjoint_paths(
    G: Any,
    s: Any,
    t: Any,
    flow_func: Any | None = ...,
    cutoff: Any | None = ...,
    auxiliary: Any | None = ...,
    residual: Any | None = ...,
) -> None: ...
