# Stubs for networkx.algorithms.connectivity.disjoint_paths (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from _typeshed import Incomplete

def edge_disjoint_paths(
    G: Incomplete,
    s: Incomplete,
    t: Incomplete,
    flow_func: Incomplete | None = ...,
    cutoff: Incomplete | None = ...,
    auxiliary: Incomplete | None = ...,
    residual: Incomplete | None = ...,
) -> None: ...
def node_disjoint_paths(
    G: Incomplete,
    s: Incomplete,
    t: Incomplete,
    flow_func: Incomplete | None = ...,
    cutoff: Incomplete | None = ...,
    auxiliary: Incomplete | None = ...,
    residual: Incomplete | None = ...,
) -> None: ...
