# Stubs for networkx.algorithms.connectivity.kcomponents (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from networkx.algorithms.flow import edmonds_karp
from typing import Any, Optional

def k_components(G: Any, flow_func: Optional[Any] = ...): ...
