# Stubs for networkx.algorithms.connectivity.kcomponents (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from _typeshed import Incomplete

def k_components(G: Incomplete, flow_func: Incomplete | None = ...) -> Incomplete: ...
