# Stubs for networkx.algorithms.connectivity.kcomponents (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

def k_components(G: Any, flow_func: Any | None = ...) -> Any: ...
