# Stubs for networkx.algorithms.connectivity.kcutsets (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

def all_node_cuts(G: Any, k: Any | None = ..., flow_func: Any | None = ...) -> None: ...
