# Stubs for networkx.algorithms.connectivity.kcutsets (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from _typeshed import Incomplete

def all_node_cuts(
    G: Incomplete, k: Incomplete | None = ..., flow_func: Incomplete | None = ...
) -> None: ...
