# Stubs for networkx.algorithms.connectivity.stoerwagner (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from _typeshed import Incomplete

def stoer_wagner(
    G: Incomplete, weight: str = ..., heap: Incomplete = ...
) -> Incomplete: ...
