# Stubs for networkx.algorithms.connectivity.utils (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from _typeshed import Incomplete

def build_auxiliary_node_connectivity(G: Incomplete) -> Incomplete: ...
def build_auxiliary_edge_connectivity(G: Incomplete) -> Incomplete: ...
