# Stubs for networkx.algorithms.shortest_paths.astar (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

def astar_path(G: Any, source: Any, target: Any, heuristic: Any | None = ..., weight: str = ...) -> Any: ...
def astar_path_length(G: Any, source: Any, target: Any, heuristic: Any | None = ..., weight: str = ...) -> Any: ...
