# Stubs for networkx.algorithms.shortest_paths.astar (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from _typeshed import Incomplete

def astar_path(
    G: Incomplete,
    source: Incomplete,
    target: Incomplete,
    heuristic: Incomplete | None = ...,
    weight: str = ...,
) -> Incomplete: ...
def astar_path_length(
    G: Incomplete,
    source: Incomplete,
    target: Incomplete,
    heuristic: Incomplete | None = ...,
    weight: str = ...,
) -> Incomplete: ...
