# Stubs for networkx.algorithms.shortest_paths.generic (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any, Optional, TypeVar, overload, List, Dict

from networkx.classes.graph import Graph

T = TypeVar('T')

def has_path(G: Any, source: Any, target: Any): ...




@overload
def shortest_path(G: Graph[T], target: T = ..., weight: Optional[Any] = ..., method: str = ...) -> Dict[T, List[T]]: ...

@overload
def shortest_path(G: Graph[T], source: T = ..., weight: Optional[Any] = ..., method: str = ...) -> Dict[T, List[T]]: ...

@overload
def shortest_path(G: Graph[T], source: T = ..., target: T = ..., weight: Optional[Any] = ..., method: str = ...) -> List[T]: ...2



def shortest_path_length(G: Any, source: Optional[Any] = ..., target: Optional[Any] = ..., weight: Optional[Any] = ..., method: str = ...): ...
def average_shortest_path_length(G: Any, weight: Optional[Any] = ..., method: str = ...): ...
def all_shortest_paths(G: Any, source: Any, target: Any, weight: Optional[Any] = ..., method: str = ...) -> None: ...
