# Stubs for networkx.algorithms.traversal.beamsearch (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from _typeshed import Incomplete

def bfs_beam_edges(
    G: Incomplete, source: Incomplete, value: Incomplete, width: Incomplete | None = ...
) -> Incomplete: ...
