# Stubs for networkx.algorithms.traversal.breadth_first_search (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from _typeshed import Incomplete

def bfs_edges(
    G: Incomplete,
    source: Incomplete,
    reverse: bool = ...,
    depth_limit: Incomplete | None = ...,
) -> None: ...
def bfs_tree(
    G: Incomplete,
    source: Incomplete,
    reverse: bool = ...,
    depth_limit: Incomplete | None = ...,
) -> Incomplete: ...
def bfs_predecessors(
    G: Incomplete, source: Incomplete, depth_limit: Incomplete | None = ...
) -> None: ...
def bfs_successors(
    G: Incomplete, source: Incomplete, depth_limit: Incomplete | None = ...
) -> None: ...
