# Stubs for networkx.algorithms.traversal.edgebfs (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from _typeshed import Incomplete

def edge_bfs(
    G: Incomplete, source: Incomplete | None = ..., orientation: Incomplete | None = ...
) -> Incomplete: ...
