# Stubs for networkx.algorithms.traversal.edgebfs (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any
from _typeshed import Incomplete

def edge_bfs(
    G: Any, source: Any | None = ..., orientation: Any | None = ...
) -> Incomplete: ...
