# Stubs for networkx.algorithms.traversal.edgedfs (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

def edge_dfs(G: Any, source: Any | None = ..., orientation: Any | None = ...) -> Any: ...
