# Stubs for networkx.algorithms.approximation.clique (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any
from _typeshed import Incomplete

def max_clique(G: Any) -> Incomplete: ...
def clique_removal(G: Any) -> Incomplete: ...
def large_clique_size(G: Any) -> Incomplete: ...
