# Stubs for networkx.algorithms.approximation.clustering_coefficient (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

def average_clustering(G: Any, trials: int = ..., seed: Any | None = ...) -> Any: ...
