# Stubs for networkx.algorithms.approximation.connectivity (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from _typeshed import Incomplete

def local_node_connectivity(
    G: Incomplete,
    source: Incomplete,
    target: Incomplete,
    cutoff: Incomplete | None = ...,
) -> Incomplete: ...
def node_connectivity(
    G: Incomplete, s: Incomplete | None = ..., t: Incomplete | None = ...
) -> Incomplete: ...
def all_pairs_node_connectivity(
    G: Incomplete, nbunch: Incomplete | None = ..., cutoff: Incomplete | None = ...
) -> Incomplete: ...
