# Stubs for networkx.algorithms.approximation.dominating_set (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

def min_weighted_dominating_set(G: Any, weight: Any | None = ...) -> Any: ...
def min_edge_dominating_set(G: Any) -> Any: ...
