# Stubs for networkx.algorithms.approximation.dominating_set (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from _typeshed import Incomplete

def min_weighted_dominating_set(
    G: Incomplete, weight: Incomplete | None = ...
) -> Incomplete: ...
def min_edge_dominating_set(G: Incomplete) -> Incomplete: ...
