# Stubs for networkx.algorithms.approximation.independent_set (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from _typeshed import Incomplete

def maximum_independent_set(G: Incomplete) -> Incomplete: ...
