# Stubs for networkx.algorithms.approximation.independent_set (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any
from _typeshed import Incomplete

def maximum_independent_set(G: Any) -> Incomplete: ...
