# Stubs for networkx.algorithms.approximation.kcomponents (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any
from _typeshed import Incomplete

def k_components(G: Any, min_density: float = ...) -> Incomplete: ...
