# Stubs for networkx.algorithms.approximation.kcomponents (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from _typeshed import Incomplete

def k_components(G: Incomplete, min_density: float = ...) -> Incomplete: ...
