# Stubs for networkx.algorithms.approximation.kcomponents (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

def k_components(G: Any, min_density: float = ...) -> Any: ...
