# Stubs for networkx.algorithms.approximation.matching (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from _typeshed import Incomplete

def min_maximal_matching(G: Incomplete) -> Incomplete: ...
