# Stubs for networkx.algorithms.approximation.ramsey (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from _typeshed import Incomplete

def ramsey_R2(G: Incomplete) -> Incomplete: ...
