# Stubs for networkx.algorithms.approximation.steinertree (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

def metric_closure(G: Any, weight: str = ...) -> Any: ...
def steiner_tree(G: Any, terminal_nodes: Any, weight: str = ...) -> Any: ...
