# Stubs for networkx.algorithms.approximation.steinertree (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from _typeshed import Incomplete

def metric_closure(G: Incomplete, weight: str = ...) -> Incomplete: ...
def steiner_tree(
    G: Incomplete, terminal_nodes: Incomplete, weight: str = ...
) -> Incomplete: ...
