# Stubs for networkx.algorithms.approximation.vertex_cover (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any
from _typeshed import Incomplete

def min_weighted_vertex_cover(G: Any, weight: Any | None = ...) -> Incomplete: ...
