name: CI
on:
  - push
  - pull_request
jobs:
  pyright:
    name: Pyright
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup python
      uses: actions/setup-python@main
    - name: Deps
      run: 'pip install -e .[test]'
    - name: Tests
      run: 'pyright -p pyrightconfig.stricter.json --pythonversion 3.7 networkx-stubs'
  flake8:
    name: Flake8
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup python
      uses: actions/setup-python@main
    - name: Deps
      run: 'pip install -e .[test]'
    - name: Tests
      run: 'flake8 networkx-stubs'
