# Stubs for networkx.generators.atlas (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any
from _typeshed import Incomplete

def graph_atlas(i: Any) -> Incomplete: ...
def graph_atlas_g() -> Incomplete: ...
