# Stubs for networkx.generators.community (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from _typeshed import Incomplete

def caveman_graph(l: Incomplete, k: Incomplete) -> Incomplete: ...
def connected_caveman_graph(l: Incomplete, k: Incomplete) -> Incomplete: ...
def relaxed_caveman_graph(
    l: Incomplete, k: Incomplete, p: Incomplete, seed: Incomplete | None = ...
) -> Incomplete: ...
def random_partition_graph(
    sizes: Incomplete,
    p_in: Incomplete,
    p_out: Incomplete,
    seed: Incomplete | None = ...,
    directed: bool = ...,
) -> Incomplete: ...
def planted_partition_graph(
    l: Incomplete,
    k: Incomplete,
    p_in: Incomplete,
    p_out: Incomplete,
    seed: Incomplete | None = ...,
    directed: bool = ...,
) -> Incomplete: ...
def gaussian_random_partition_graph(
    n: Incomplete,
    s: Incomplete,
    v: Incomplete,
    p_in: Incomplete,
    p_out: Incomplete,
    directed: bool = ...,
    seed: Incomplete | None = ...,
) -> Incomplete: ...
def ring_of_cliques(num_cliques: Incomplete, clique_size: Incomplete) -> Incomplete: ...
def windmill_graph(n: Incomplete, k: Incomplete) -> Incomplete: ...
def stochastic_block_model(
    sizes: Incomplete,
    p: Incomplete,
    nodelist: Incomplete | None = ...,
    seed: Incomplete | None = ...,
    directed: bool = ...,
    selfloops: bool = ...,
    sparse: bool = ...,
) -> Incomplete: ...
