# Stubs for networkx.generators.duplication (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from _typeshed import Incomplete

def partial_duplication_graph(
    N: Incomplete,
    n: Incomplete,
    p: Incomplete,
    q: Incomplete,
    seed: Incomplete | None = ...,
) -> Incomplete: ...
def duplication_divergence_graph(
    n: Incomplete, p: Incomplete, seed: Incomplete | None = ...
) -> Incomplete: ...
