# Stubs for networkx.generators.expanders (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

def margulis_gabber_galil_graph(n: Any, create_using: Any | None = ...) -> Any: ...
def chordal_cycle_graph(p: Any, create_using: Any | None = ...) -> Any: ...
