# Stubs for networkx.generators.geometric (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

def random_geometric_graph(
    n: Any,
    radius: Any,
    dim: int = ...,
    pos: Any | None = ...,
    p: int = ...,
    seed: Any | None = ...,
) -> Incomplete: ...
def soft_random_geometric_graph(
    n: Any,
    radius: Any,
    dim: int = ...,
    pos: Any | None = ...,
    p: int = ...,
    p_dist: Any | None = ...,
    seed: Any | None = ...,
) -> Incomplete: ...
def geographical_threshold_graph(
    n: Any,
    theta: Any,
    dim: int = ...,
    pos: Any | None = ...,
    weight: Any | None = ...,
    metric: Any | None = ...,
    p_dist: Any | None = ...,
    seed: Any | None = ...,
) -> Incomplete: ...
def waxman_graph(
    n: Any,
    beta: float = ...,
    alpha: float = ...,
    L: Any | None = ...,
    domain: Any = ...,
    metric: Any | None = ...,
    seed: Any | None = ...,
) -> Incomplete: ...
def navigable_small_world_graph(
    n: Any,
    p: int = ...,
    q: int = ...,
    r: int = ...,
    dim: int = ...,
    seed: Any | None = ...,
) -> Incomplete: ...
def thresholded_random_geometric_graph(
    n: Any,
    radius: Any,
    theta: Any,
    dim: int = ...,
    pos: Any | None = ...,
    weight: Any | None = ...,
    p: int = ...,
    seed: Any | None = ...,
) -> Incomplete: ...
