# Stubs for networkx.generators.harary_graph (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

def hnm_harary_graph(n: Any, m: Any, create_using: Any | None = ...) -> Any: ...
def hkn_harary_graph(k: Any, n: Any, create_using: Any | None = ...) -> Any: ...
