# Stubs for networkx.generators.joint_degree_seq (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from _typeshed import Incomplete

def is_valid_joint_degree(joint_degrees: Incomplete) -> Incomplete: ...
def joint_degree_graph(
    joint_degrees: Incomplete, seed: Incomplete | None = ...
) -> Incomplete: ...
