# Stubs for networkx.generators.joint_degree_seq (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

def is_valid_joint_degree(joint_degrees: Any) -> Any: ...
def joint_degree_graph(joint_degrees: Any, seed: Any | None = ...) -> Any: ...
