# Stubs for networkx.generators.lattice (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from _typeshed import Incomplete

def grid_2d_graph(
    m: Incomplete,
    n: Incomplete,
    periodic: bool = ...,
    create_using: Incomplete | None = ...,
) -> Incomplete: ...
def grid_graph(dim: Incomplete, periodic: bool = ...) -> Incomplete: ...
def hypercube_graph(n: Incomplete) -> Incomplete: ...
def triangular_lattice_graph(
    m: Incomplete,
    n: Incomplete,
    periodic: bool = ...,
    with_positions: bool = ...,
    create_using: Incomplete | None = ...,
) -> Incomplete: ...
def hexagonal_lattice_graph(
    m: Incomplete,
    n: Incomplete,
    periodic: bool = ...,
    with_positions: bool = ...,
    create_using: Incomplete | None = ...,
) -> Incomplete: ...
