# Stubs for networkx.generators.line (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

from networkx.utils.decorators import *

def line_graph(G: Any, create_using: Any | None = ...) -> Any: ...
def inverse_line_graph(G: Any) -> Any: ...
