# Stubs for networkx.generators.mycielski (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from _typeshed import Incomplete

def mycielskian(G: Incomplete, iterations: int = ...) -> Incomplete: ...
def mycielski_graph(n: Incomplete) -> Incomplete: ...
