# Stubs for networkx.generators.nonisomorphic_trees (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from _typeshed import Incomplete

def nonisomorphic_trees(order: Incomplete, create: str = ...) -> None: ...
def number_of_nonisomorphic_trees(order: Incomplete) -> Incomplete: ...
