# Stubs for networkx.generators.random_clustered (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

def random_clustered_graph(joint_degree_sequence: Any, create_using: Any | None = ..., seed: Any | None = ...) -> Any: ...
