# Stubs for networkx.generators.random_clustered (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from _typeshed import Incomplete

def random_clustered_graph(
    joint_degree_sequence: Incomplete,
    create_using: Incomplete | None = ...,
    seed: Incomplete | None = ...,
) -> Incomplete: ...
