# Stubs for networkx.generators.spectral_graph_forge (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from _typeshed import Incomplete

def spectral_graph_forge(
    G: Incomplete,
    alpha: Incomplete,
    transformation: str = ...,
    seed: Incomplete | None = ...,
) -> Incomplete: ...
