# Stubs for networkx.generators.spectral_graph_forge (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

def spectral_graph_forge(G: Any, alpha: Any, transformation: str = ..., seed: Any | None = ...) -> Any: ...
