# Stubs for networkx.generators.stochastic (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any
from _typeshed import Incomplete

def stochastic_graph(G: Any, copy: bool = ..., weight: str = ...) -> Incomplete: ...
