# Stubs for networkx.generators.stochastic (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from _typeshed import Incomplete

def stochastic_graph(
    G: Incomplete, copy: bool = ..., weight: str = ...
) -> Incomplete: ...
