# Stubs for networkx.generators.trees (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

def prefix_tree(paths: Any) -> Any: ...
def random_tree(n: Any, seed: Any | None = ...) -> Any: ...
