# Stubs for networkx.generators.trees (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any
from _typeshed import Incomplete

def prefix_tree(paths: Any) -> Incomplete: ...
def random_tree(n: Any, seed: Any | None = ...) -> Incomplete: ...
