# Stubs for networkx.generators.triads (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from _typeshed import Incomplete

def triad_graph(triad_name: Incomplete) -> Incomplete: ...
